# Site settings
title: Your awesome title
email: exec@socis.ca
description: "We are the Society of Computing and Information Science, a student organization for the University of Guelph's School of Computer Science."
url: "http://socis.ca"
facebook_url: "https://www.facebook.com/groups/UoGSOCIS/"
twitter_url: "https://twitter.com/uogsocis"
instagram_url: "https://www.instagram.com/socis.uog/"

# Build settings
markdown: redcarpet
permalink: /posts/:year/:month/:day/:title
timezone: America/New_York
future: true
